### ISSUE TITLE
Crash when calling up map

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#52]
It seems to only ever happen after I've failed to meet a delivery or escort deadline.  I arrive in a system, receive notification that I've missed a deadline, I press 'm' to bring up my map, and the game immediately disappears.  This happens pretty consistently, both with 0.7.11 and with git version fd119b44732f47c70131fc00e924c72dc18f3efb.

Here's the gdb output:
```
(gdb) run
Starting program: /home/john/endless-sky-git/endless-sky 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[New Thread 0x7fffefca3700 (LWP 16671)]
[New Thread 0x7fffef4a2700 (LWP 16672)]
[New Thread 0x7fffeeca1700 (LWP 16673)]
[New Thread 0x7fffee4a0700 (LWP 16674)]
[New Thread 0x7fffea67a700 (LWP 16675)]
[New Thread 0x7fffe9e79700 (LWP 16676)]
[Thread 0x7fffe9e79700 (LWP 16676) exited]
[New Thread 0x7fffe9e79700 (LWP 16677)]
[New Thread 0x7fffe9678700 (LWP 16678)]
[New Thread 0x7fffe8e77700 (LWP 16679)]
[Thread 0x7fffe8e77700 (LWP 16679) exited]
[New Thread 0x7fffcf20f700 (LWP 16681)]

Program received signal SIGFPE, Arithmetic exception.
0x00000000004a7047 in MapPanel::DrawMissions() const ()
(gdb) bt
#0  0x00000000004a7047 in MapPanel::DrawMissions() const ()
#1  0x00000000004a76a7 in MapPanel::Draw() const ()
#2  0x000000000049ef59 in MapDetailPanel::Draw() const ()
#3  0x000000000051cc9d in UI::DrawAll() ()
#4  0x000000000040b1ae in main ()
```

![screenshot from 2015-06-19 18 11 43](https://cloud.githubusercontent.com/assets/692397/8264663/b7bd2b2c-16ae-11e5-85e2-57018e085875.png)

**Comment by endless-sky** [comment]
Looks like a divide-by-zero in my code for blinking the mission pointer, when it's exactly one day after the deadline (i.e. the mission just failed). Commit de7c8f4 should fix that.

**Comment by johndh** [comment]
That seems to have fixed it.  I've tested it and I no longer get the crash.
