### ISSUE TITLE
Crash when buying goods on Terra Incognita

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#61]
After passing through Over The Rainbow and landing on the abandoned spaceport on Terra Incognita, trade goods are listed as price 0, and clicking to buy them produces a crash.

```
john@ProBook ~/endless-sky-git $ gdb !!
gdb ./endless-sky
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./endless-sky...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/john/endless-sky-git/endless-sky 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[New Thread 0x7fffefca3700 (LWP 4941)]
[New Thread 0x7fffef4a2700 (LWP 4942)]
[New Thread 0x7fffeeca1700 (LWP 4943)]
[New Thread 0x7fffee4a0700 (LWP 4944)]
[New Thread 0x7fffea67a700 (LWP 4945)]
[New Thread 0x7fffe9e79700 (LWP 4946)]
[Thread 0x7fffe9e79700 (LWP 4946) exited]
[New Thread 0x7fffe9e79700 (LWP 4947)]
[New Thread 0x7fffe9678700 (LWP 4948)]
[New Thread 0x7fffe8e77700 (LWP 4949)]
[Thread 0x7fffe8e77700 (LWP 4949) exited]
[New Thread 0x7fffcf20f700 (LWP 4951)]

Program received signal SIGFPE, Arithmetic exception.
0x0000000000522594 in TradingPanel::Buy(long) ()
(gdb) bt
#0  0x0000000000522594 in TradingPanel::Buy(long) ()
#1  0x00000000005244d8 in TradingPanel::Click(int, int) ()
#2  0x000000000052482d in UI::Handle(SDL_Event const&) ()
#3  0x000000000040c030 in main ()
```

**Comment by endless-sky** [comment]
I've modified the trading panel to not allow you to buy or sell commodities for which no price is specified (26217cb).
